INSERT INTO TB_SEXO (ID, DESCRICAO) VALUES (1, 'Masculino');
INSERT INTO TB_SEXO (ID, DESCRICAO) VALUES (2, 'Feminino');

INSERT INTO TB_ESTADO_CIVIL (ID, DESCRICAO) VALUES (1, 'Solteiro (a)');
INSERT INTO TB_ESTADO_CIVIL (ID, DESCRICAO) VALUES (2, 'Casado (a)');
INSERT INTO TB_ESTADO_CIVIL (ID, DESCRICAO) VALUES (3, 'Divorciado (a)');
INSERT INTO TB_ESTADO_CIVIL (ID, DESCRICAO) VALUES (4, 'Viúvo (a)');
